name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/profile pic.jpg
    - assets/logo_title_slogan.png
    - assets/logo_title.png
    - assets/icon.png
    - assets/brand_slogan.png
    - assets/slogan.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
